services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  querys_in_fastapi:
    build: ./querys_in_fastapi
    environment:
      DB_HOST: localhost
      DB_USER: "root"
      DB_PORT: 3306
      DB_PASSWORD: "root"
      DB_NAME: "digital_hunter"
    depends_on:
      - elasticsearch